plugins:
  - jekyll-default-layout

title: Yet Another Limbus Company Tier List
description: By a stats-obsessed psychopath.
theme: just-the-docs

url: https://null-machine.github.io/limbus-company-roll-analyzer/